package com.doctorsplaza.app.utils

//const val BASE_URL = "http://65.0.71.39:5000/api/"
const val BASE_URL = "https://test.doctorsplaza.in/api/"

const val DATE_FULL_PATTERN = "yyyy-MM-dd'T'HH:mm:ss"
const val DATE_PATTERN = "yyyy-MM-dd"
const val REMINDER_DATE_MONTH_PATTERN2 = "dd-MM-yyyy hh:mm aaa"

// patient register
const val PatientId = "id"
const val Patient_Id = "patientId"
const val PatientName = "patientName"
const val PatientEmail = "email"
const val PatientPassword = "password"
const val PatientBloodGroup = "bloodGroup"
const val PatientGender = "gender"
const val PatientAddress = "address"
const val PatientAge = "age"
const val PatientDOB = "dob"
const val PatientContactNumber = "contactNumber"
const val PatientToken = "token"
const val PatientOtp = "otp"
const val DoctorName = "doctorName"
const val DepartmentName = "departmentName"
const val DoctorNo = "phoneNo"
const val DoctorState = "state"
const val DoctorCity = "city"
const val DoctorPincode = "pincode"
const val DoctorFees = "consultationfee"
const val DoctorExperience = "experience"
